# Generated by Django 3.0.2 on 2020-01-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unamedTodo', max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('Todo_date', models.DateTimeField(verbose_name='Todo Date')),
                ('pub_date', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
