# Generated by Django 3.0.2 on 2020-01-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default='unamedTodo', max_length=100),
        ),
    ]
